[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]

[tool.pylint.format]
max-line-length = "120"

[tool.black]
line-length = "120"
extend-exclude = "\\.ipynb"

[tool.pyright]
venv = ".venv"
venvPath = "./"
# TODO fix this, throwing errors in fixed_point.py
# typeCheckingMode = "strict"
exclude = [
    ".venv",
    ".vscode",
    "docs",
]

[tool.ruff]
# Default is: pycodestyle (E) and Pyflakes (F)
# We add flake8-builtins (A), pydocstyle (D), isort (I), pep8-naming (N), and pylint (PL).
# We remove pycodestyle (E) since it throws erroneous line too long errors.
# We remove Pyflakes (F) since it complains about `import *` which we need.
select = ["A", "D", "I", "N", "PL"]

# We ignore the following rules:
# D203 : 1 blank line required before class docstring (incompatible with D211: no blank lines before class docstring)
# D213: multi-line-summary-second-line (incompatible with D212: multi-line summary should start at the first line)
# D416: section-name-ends-in-colon (numpy style guide doesn't use colons after sections, i.e. Parameters)
ignore = ["D203", "D213", "D416"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "D", "I", "N", "PL"]
unfixable = []

# override pow in fixed_point, and allow literal comparison in tests
per-file-ignores = { "lib/fixedpointmath/fixedpointmath/fixed_point.py" = [
    "A003",
], "lib/fixedpointmath/tests/*" = [
    "PLR2004",
] }

# Ignore builtins in elfpy/utils/math/fixed_point.py
line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"

exclude = [
    ".venv",
    ".vscode",
]
